### ISSUE TITLE
Always Uncaught TypeError: treeView.serialize is not a function

### ISSUE THREAD

**Issue by marqusG** [colonelpopcorn/tortoise-hg#1] opened 2018-06-13 07:20 UTC
Whatever command I try to use from the right-click menu (both in folders and in files) I get this error:

`Uncaught TypeError: treeView.serialize is not a function
/home/marco/.atom/packages/tortoise-hg/lib/tortoise-hg.coffee:47
Hide Stack Trace
TypeError: treeView.serialize is not a function
    at resolveTreeSelection (/home/marco/.atom/packages/tortoise-hg/lib/tortoise-hg.coffee:47:27)
    at Object.workbenchFromTreeView (/home/marco/.atom/packages/tortoise-hg/lib/tortoise-hg.coffee:285:16)
    at HTMLElement.atom.commands.add.tortoise-hg:workbenchFromTreeView (/home/marco/.atom/packages/tortoise-hg/lib/tortoise-hg.coffee:205:82)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1351:25)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:346:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)`

**Comment by colonelpopcorn** [comment] 2018-06-13 13:27
Could I get the Atom version number you are using?

**Comment by marqusG** [comment] 2018-06-13 13:52
HI colonelpopcorn. My Atom version number is 1.27.2, the latest I could install using apt on my Linux Mint

**Comment by marqusG** [comment] 2018-06-13 15:20
I've just realized that your package is for Windows only :(

**Comment by colonelpopcorn** [comment] 2018-06-13 19:50
It theoretically supports Linux. I'll spin up a VM and try to reproduce the issue. Hopefully I can get it updated to the latest Atom API calls.

**Comment by colonelpopcorn** [comment] 2018-07-11 03:55
Hey @marqusG ,
I tried this on my Ubuntu install and was able to reproduce the issue. The problem was with the serialize function being deprecated. I've since fixed the issue and published a new version. Can you try this out on your machine and let me know if it works?

**Comment by marqusG** [comment] 2018-07-11 08:02
Hi, colonelpopcorn. I'll try it asap and let you know. Thank you :)

**Comment by marqusG** [comment] 2018-07-14 17:39
You fixed it! It works like a charm and I like it much more than the Mercurial plugin I have in VS Code. hank you so much for your work! Cheers

**Comment by colonelpopcorn** [comment] 2018-07-15 21:57
Awesome, closing this issue!

**Closed as completed by colonelpopcorn** 2018-07-15 21:57 UTC
